name: deploy

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download Exiled Installer
        run: wget https://github.com/Exiled-Team/EXILED/releases/download/5.3.0-beta.4/Exiled.Installer-Linux
      - 
        name: create directory
        run: mkdir containers
      -
        name: Build and push latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./latest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:latest
      -
        name: Build and push slim version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./slim/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:slim
      -
        name: save latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          outputs: type=tar,dest=containers/latest.tar
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:latest
      -
        name: save slim version
        uses: docker/build-push-action@v2
        with:
          context: .
          outputs: type=tar,dest=containers/slim.tar
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:slim
      - 
        name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: containers
            path: containers
 
