name: deploy

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./latest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:latest
      -
        name: Build and push slim version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./slim/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:slim
 
      -
        name: Build and push pterodactyl version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pterodactyl/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:pterodactyl
      -
        name: Build and push pterodactyl slim version
        uses: docker/build-push-action@v2
        with:
          context: .  
          file: ./pterodactyl-slim/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:pterodactyl-slim
