name: pterodactyl-ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build test
        run: docker build . --file ./pterodactyl/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:pterodactyl
      -
        name: Save build
        run: docker save ${{ secrets.DOCKER_HUB_USERNAME }}/scpsl-server:pterodactyl | gzip > container.tar.gz
      - 
        name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: container
            path: container.tar.gz
