name: slim-ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        run: wget https://github.com/Exiled-Team/EXILED/releases/download/5.3.0-beta.4/Exiled.Installer-Linux
      -
        name: Build test
        uses: actions/checkout@v3
        run: docker build . --file ./slim/Dockerfile --tag angryagent/scpsl-server:slim
      -
        name: Save build
        run: docker save angryagent/scpsl-server:slim | gzip > container.tar.gz
      - 
        name: upload artifactuses
        uses: actions/upload-artifact@v3
        with:
            name: container
            path: container.tar.gz

